language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  - DB=mysql

before_script:
  - sudo apt-get update -qq
  - sudo apt-get upgrade -y -qq
  - composer self-update
  - composer install
  - if [[ "$DB" == "mysql" ]]; then mysql -uroot < yfrdb.sql; fi
script: phpunit
