language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - DB=mysql

before_script:
  - composer self-update
  - composer install
  - if [[ "$DB" == "mysql" ]]; then mysql -uroot -e "create database IF NOT EXISTS yfrdb;";mysql -uroot yfrdb < ./app/tests/yfrdb.sql; fi
script: phpunit
